/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,jsx}",
    "./src/components/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e5e2e1",
        "surface-bright": "#fdf8f8",
        "on-secondary-fixed-variant": "#474747",
        "on-tertiary": "#ffffff",
        background: "#fdf8f8",
        "tertiary-container": "#1d1b1a",
        "pure-white": "#FFFFFF",
        "secondary-fixed-dim": "#c8c6c6",
        "surface-variant": "#e5e2e1",
        "inverse-on-surface": "#f4f0ef",
        "outline-variant": "#c4c7c7",
        error: "#ba1a1a",
        "inverse-primary": "#c8c6c5",
        "on-tertiary-fixed": "#1d1b1a",
        surface: "#fdf8f8",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#c8c6c5",
        "on-secondary": "#ffffff",
        "mid-gray": "#8A8A8A",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#313030",
        "surface-container": "#f1edec",
        "secondary-fixed": "#e4e2e1",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e6e1df",
        "surface-dim": "#ddd9d8",
        "tertiary-fixed-dim": "#cac6c3",
        "on-background": "#1c1b1b",
        "surface-tint": "#5f5e5e",
        "on-surface-variant": "#444748",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "on-surface": "#1c1b1b",
        "on-primary-fixed-variant": "#474646",
        tertiary: "#000000",
        outline: "#747878",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#1b1c1c",
        "primary-fixed": "#e5e2e1",
        "on-tertiary-fixed-variant": "#484645",
        "secondary-container": "#e4e2e1",
        secondary: "#5f5e5e",
        "on-secondary-container": "#656464",
        "surface-gray": "#F5F5F5",
        "surface-container-high": "#ebe7e6",
        "line-gray": "#E3E3E3",
        "surface-container-low": "#f7f3f2",
        "on-primary-fixed": "#1c1b1b",
        primary: "#000000",
        "on-tertiary-container": "#868381",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        "card-padding": "16px",
        "list-gap": "8px",
        "container-padding-mobile": "16px",
        "section-gap": "32px",
        unit: "8px",
      },
      fontFamily: {
        display: ["Plus Jakarta Sans"],
        "headline-h1": ["Plus Jakarta Sans"],
        "headline-h2-mobile": ["Plus Jakarta Sans"],
        caption: ["Plus Jakarta Sans"],
        "headline-h1-mobile": ["Plus Jakarta Sans"],
        "display-mobile": ["Plus Jakarta Sans"],
        "headline-h2": ["Plus Jakarta Sans"],
        body: ["Plus Jakarta Sans"],
        button: ["Plus Jakarta Sans"],
        "body-mobile": ["Plus Jakarta Sans"],
      },
      fontSize: {
        display: ["36px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-h1": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-h2-mobile": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        caption: ["13px", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-h1-mobile": ["22px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-h2": ["22px", { lineHeight: "1.4", fontWeight: "600" }],
        body: ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        button: ["16px", { lineHeight: "1", fontWeight: "500" }],
        "body-mobile": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
